/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.gltf 
Author: zam205 (https://sketchfab.com/zam205)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-with-code-0a06208ac22b45c4814dea46b6fc6b0a
Title: laptop with code
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

const Model = (props) => {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/laptop.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="root_1">
                  <group
                    name="GLTF_SceneRootNode_2"
                    rotation={[Math.PI / 2, 0, 0]}
                  >
                    <group
                      name="Armature002_11_3"
                      position={[0, -0.122, -1.257]}
                      rotation={[-Math.PI / 2, 0, 0]}
                    >
                      <group name="GLTF_created_0_4">
                        <group name="GLTF_created_0">
                          <primitive object={nodes.GLTF_created_0_rootJoint} />
                          <group name="Object_7_7_correction">
                            <group name="Object_7_7" />
                          </group>
                          <group name="Object_8_8_correction">
                            <group name="Object_8_8" />
                          </group>
                          <group name="Object_9_9_correction">
                            <group name="Object_9_9" />
                          </group>
                          <group name="Object_10_10_correction">
                            <group name="Object_10_10" />
                          </group>
                          <group name="Object_11_11_correction">
                            <group name="Object_11_11" />
                          </group>
                          <group name="Object_12_12_correction">
                            <group name="Object_12_12" />
                          </group>
                          <group name="Object_13_13_correction">
                            <group name="Object_13_13" />
                          </group>
                          <group name="Object_14_14_correction">
                            <group name="Object_14_14" />
                          </group>
                          <group name="Object_15_15_correction">
                            <group name="Object_15_15" />
                          </group>
                          <group name="Object_16_16_correction">
                            <group name="Object_16_16" />
                          </group>
                          <group name="Object_17_17_correction">
                            <group name="Object_17_17" />
                          </group>
                          <group name="Object_18_18_correction">
                            <group name="Object_18_18" />
                          </group>
                          <group name="Object_19_19_correction">
                            <group name="Object_19_19" />
                          </group>
                          <group name="Object_20_20_correction">
                            <group name="Object_20_20" />
                          </group>
                          <group name="Object_21_21_correction">
                            <group name="Object_21_21" />
                          </group>
                          <group name="Object_22_22_correction">
                            <group name="Object_22_22" />
                          </group>
                          <group name="Object_23_23_correction">
                            <group name="Object_23_23" />
                          </group>
                          <group name="Object_24_24_correction">
                            <group name="Object_24_24" />
                          </group>
                          <group name="Object_25_25_correction">
                            <group name="Object_25_25" />
                          </group>
                          <group name="Object_26_26_correction">
                            <group name="Object_26_26" />
                          </group>
                          <group name="Object_27_27_correction">
                            <group name="Object_27_27" />
                          </group>
                          <group name="Object_28_28_correction">
                            <group name="Object_28_28" />
                          </group>
                          <group name="Object_29_29_correction">
                            <group name="Object_29_29" />
                          </group>
                          <group name="Object_31_31_correction">
                            <group name="Object_31_31" />
                          </group>
                          <group name="Object_33_33_correction">
                            <group name="Object_33_33" />
                          </group>
                          <group name="Object_34_34_correction">
                            <group name="Object_34_34" />
                          </group>
                          <group name="Object_35_35_correction">
                            <group name="Object_35_35" />
                          </group>
                          <group name="Object_36_36_correction">
                            <group name="Object_36_36" />
                          </group>
                          <group name="Object_37_37_correction">
                            <group name="Object_37_37" />
                          </group>
                          <group name="Object_38_38_correction">
                            <group name="Object_38_38" />
                          </group>
                          <group name="Object_39_39_correction">
                            <group name="Object_39_39" />
                          </group>
                          <group name="Object_40_40_correction">
                            <group name="Object_40_40" />
                          </group>
                          <group name="Object_41_41_correction">
                            <group name="Object_41_41" />
                          </group>
                          <skinnedMesh
                            name="Object_16"
                            geometry={nodes.Object_16.geometry}
                            material={materials.body}
                            skeleton={nodes.Object_16.skeleton}
                          />
                          <skinnedMesh
                            name="Object_19"
                            geometry={nodes.Object_19.geometry}
                            material={materials.motif}
                            skeleton={nodes.Object_19.skeleton}
                          />
                          <skinnedMesh
                            name="Object_22"
                            geometry={nodes.Object_22.geometry}
                            material={materials.blacc}
                            skeleton={nodes.Object_22.skeleton}
                          />
                          <skinnedMesh
                            name="Object_25"
                            geometry={nodes.Object_25.geometry}
                            material={materials.motif_non}
                            skeleton={nodes.Object_25.skeleton}
                          />
                          <skinnedMesh
                            name="Object_28"
                            geometry={nodes.Object_28.geometry}
                            material={materials.kaki}
                            skeleton={nodes.Object_28.skeleton}
                          />
                          <skinnedMesh
                            name="Object_31"
                            geometry={nodes.Object_31.geometry}
                            material={materials.text}
                            skeleton={nodes.Object_31.skeleton}
                          />
                          <skinnedMesh
                            name="Object_34"
                            geometry={nodes.Object_34.geometry}
                            material={materials.light_on}
                            skeleton={nodes.Object_34.skeleton}
                          />
                          <skinnedMesh
                            name="Object_37"
                            geometry={nodes.Object_37.geometry}
                            material={materials.off_light}
                            skeleton={nodes.Object_37.skeleton}
                          />
                          <skinnedMesh
                            name="Object_40"
                            geometry={nodes.Object_40.geometry}
                            material={materials["usb.001"]}
                            skeleton={nodes.Object_40.skeleton}
                          />
                          <skinnedMesh
                            name="Object_43"
                            geometry={nodes.Object_43.geometry}
                            material={materials["Material.005"]}
                            skeleton={nodes.Object_43.skeleton}
                          />
                          <skinnedMesh
                            name="Object_46"
                            geometry={nodes.Object_46.geometry}
                            material={materials.metal_lagi}
                            skeleton={nodes.Object_46.skeleton}
                          />
                          <skinnedMesh
                            name="Object_49"
                            geometry={nodes.Object_49.geometry}
                            material={materials.metal}
                            skeleton={nodes.Object_49.skeleton}
                          />
                          <skinnedMesh
                            name="Object_52"
                            geometry={nodes.Object_52.geometry}
                            material={materials.plasct}
                            skeleton={nodes.Object_52.skeleton}
                          />
                          <skinnedMesh
                            name="Object_55"
                            geometry={nodes.Object_55.geometry}
                            material={materials.pendingin_keknya}
                            skeleton={nodes.Object_55.skeleton}
                          />
                          <skinnedMesh
                            name="Object_58"
                            geometry={nodes.Object_58.geometry}
                            material={materials.pendingin_keknya}
                            skeleton={nodes.Object_58.skeleton}
                          />
                          <skinnedMesh
                            name="Object_61"
                            geometry={nodes.Object_61.geometry}
                            material={materials.pendingin_keknya}
                            skeleton={nodes.Object_61.skeleton}
                          />
                          <skinnedMesh
                            name="Object_64"
                            geometry={nodes.Object_64.geometry}
                            material={materials.pendingin_keknya}
                            skeleton={nodes.Object_64.skeleton}
                          />
                          <skinnedMesh
                            name="Object_67"
                            geometry={nodes.Object_67.geometry}
                            material={materials.pendingin_keknya}
                            skeleton={nodes.Object_67.skeleton}
                          />
                          <skinnedMesh
                            name="Object_70"
                            geometry={nodes.Object_70.geometry}
                            material={materials["blacc.001"]}
                            skeleton={nodes.Object_70.skeleton}
                          />
                          <skinnedMesh
                            name="Object_73"
                            geometry={nodes.Object_73.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_73.skeleton}
                          />
                          <skinnedMesh
                            name="Object_76"
                            geometry={nodes.Object_76.geometry}
                            material={materials.material_16}
                            skeleton={nodes.Object_76.skeleton}
                          />
                          <skinnedMesh
                            name="Object_79"
                            geometry={nodes.Object_79.geometry}
                            material={materials.motif_v23}
                            skeleton={nodes.Object_79.skeleton}
                          />
                          <skinnedMesh
                            name="Object_82"
                            geometry={nodes.Object_82.geometry}
                            material={materials.Material}
                            skeleton={nodes.Object_82.skeleton}
                          />
                          <skinnedMesh
                            name="Object_85"
                            geometry={nodes.Object_85.geometry}
                            material={materials.body}
                            skeleton={nodes.Object_85.skeleton}
                          />
                          <skinnedMesh
                            name="Object_88"
                            geometry={nodes.Object_88.geometry}
                            material={materials.body}
                            skeleton={nodes.Object_88.skeleton}
                          />
                          <skinnedMesh
                            name="Object_91"
                            geometry={nodes.Object_91.geometry}
                            material={materials.motif}
                            skeleton={nodes.Object_91.skeleton}
                          />
                          <skinnedMesh
                            name="Object_94"
                            geometry={nodes.Object_94.geometry}
                            material={materials.motif_2}
                            skeleton={nodes.Object_94.skeleton}
                          />
                          <skinnedMesh
                            name="Object_97"
                            geometry={nodes.Object_97.geometry}
                            material={materials.display_q}
                            skeleton={nodes.Object_97.skeleton}
                          />
                          <skinnedMesh
                            name="Object_100"
                            geometry={nodes.Object_100.geometry}
                            material={materials.display_mirror}
                            skeleton={nodes.Object_100.skeleton}
                          />
                          <skinnedMesh
                            name="Object_103"
                            geometry={nodes.Object_103.geometry}
                            material={materials.layar}
                            skeleton={nodes.Object_103.skeleton}
                          />
                          <skinnedMesh
                            name="Object_106"
                            geometry={nodes.Object_106.geometry}
                            material={materials.Material}
                            skeleton={nodes.Object_106.skeleton}
                          />
                          <skinnedMesh
                            name="Object_109"
                            geometry={nodes.Object_109.geometry}
                            material={materials["Material.012"]}
                            skeleton={nodes.Object_109.skeleton}
                          />
                          <skinnedMesh
                            name="Object_112"
                            geometry={nodes.Object_112.geometry}
                            material={materials["Material.013"]}
                            skeleton={nodes.Object_112.skeleton}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/laptop.gltf");
export { Model };
