/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.gltf
Author: zam205 (https://sketchfab.com/zam205)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-with-code-0a06208ac22b45c4814dea46b6fc6b0a
Title: laptop with code
*/

import { useMemo, useRef } from "react";
import type { ComponentPropsWithoutRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group, MeshStandardMaterial } from "three";
import { SkeletonUtils } from "three-stdlib";

const Model = (props: ComponentPropsWithoutRef<"group">) => {
  const group = useRef<Group>(null);
  const { scene } = useGLTF("/laptop.gltf");
  const clonedScene = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  const silverMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: "#d8d8d8",
        metalness: 0.95,
        roughness: 0.18,
        emissive: "#000000",
      }),
    [],
  );

  useMemo(() => {
    clonedScene.traverse((child) => {
      if ("isMesh" in child && child.isMesh) {
        const mesh = child as unknown as {
          material: MeshStandardMaterial;
        };
        mesh.material = silverMaterial;
      }
    });
  }, [clonedScene, silverMaterial]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.15, 0]} scale={[0.6, 0.6, 0.6]}>
        <group rotation={[0.25, 0, 0]} position={[0, 0.15, 0.1]}>
          <primitive object={clonedScene} />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/laptop.gltf");
export { Model };
